import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
const $=s=>document.querySelector(s), canvas=$('#arenaCanvas'), arena=$('#arena'), err=$('#webglError');
const scoreEl=$('#score'),roundEl=$('#round'),livesEl=$('#lives'),comboEl=$('#combo'),coinsEl=$('#coins'),answersEl=$('#answers'),feedback=$('#feedback'),difficulty=$('#difficulty'),status=$('#statusText');
const replay=$('#replayBtn'),slow=$('#slowBtn'),restartBtn=$('#restartBtn'),shop=$('#shopDialog'),charShop=$('#characterShop'),trickShop=$('#trickShop'),shopCoins=$('#shopCoins'),shopMsg=$('#shopMessage');
const SAVE='trickJudgeSaveV3',base={coins:0,ownedCharacters:['rookie'],equippedCharacter:'rookie',ownedTricks:['backflip','frontflip','sideflip','spin360']};
let save=(()=>{try{return {...base,...JSON.parse(localStorage.getItem(SAVE)||localStorage.getItem('trickJudgeSaveV2')||'{}')}}catch{return {...base}}})();
const persist=()=>localStorage.setItem(SAVE,JSON.stringify(save));
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'})}catch(e){err.classList.remove('hidden');throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x101b27);scene.fog=new THREE.Fog(0x101b27,16,38);
const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(0,4.5,12.4);camera.lookAt(0,2.25,0);
scene.add(new THREE.HemisphereLight(0xc7dcff,0x202832,2.1));
const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(-5,10,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);
const fill=new THREE.DirectionalLight(0x75bfff,.9);fill.position.set(5,4,6);scene.add(fill);const rim=new THREE.DirectionalLight(0x8bf5d1,1.1);rim.position.set(6,6,-4);scene.add(rim);
const mk=(g,m,cast=true)=>{const o=new THREE.Mesh(g,m);o.castShadow=cast;return o}, std=(c,r=.8,metal=.02)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:metal});
const floor=mk(new THREE.PlaneGeometry(26,16),std(0x222b35,.94),false);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const runway=mk(new THREE.BoxGeometry(13,.09,3.25),std(0x596675,.72,.08),false);runway.position.y=.045;runway.receiveShadow=true;scene.add(runway);
const border=mk(new THREE.BoxGeometry(13.15,.025,3.42),std(0xcbd4df,.5,.12),false);border.position.y=.092;scene.add(border);
for(const x of [-5.2,0,5.2]){const l=mk(new THREE.BoxGeometry(.045,.012,3.08),new THREE.MeshBasicMaterial({color:0xeaf0f8,transparent:true,opacity:.38}),false);l.position.set(x,.1,0);scene.add(l)}
const wall=mk(new THREE.PlaneGeometry(28,10.5),std(0x1b2734,.98),false);wall.position.set(0,5,-6.4);scene.add(wall);
const glow=mk(new THREE.PlaneGeometry(18,4.4),new THREE.MeshBasicMaterial({color:0x417a86,transparent:true,opacity:.13}),false);glow.position.set(0,5.3,-6.3);scene.add(glow);
const metal=std(0x4a5868,.45,.7);for(const [w,h,d,x,y,z] of [[19,.12,.12,0,8.25,-1.5],[.12,3.6,.12,-9.4,6.45,-1.5],[.12,3.6,.12,9.4,6.45,-1.5],[19,.12,.12,0,5.05,-6.15]]){const b=mk(new THREE.BoxGeometry(w,h,d),metal,false);b.position.set(x,y,z);scene.add(b)}
const crowdGeo=new THREE.SphereGeometry(.12,8,6),crowdMat=[0x27313d,0x35404d,0x414c58,0x1e2630].map(c=>std(c,1));for(let r=0;r<8;r++)for(let i=0;i<40;i++){const p=mk(crowdGeo,crowdMat[(i+r)%4],false);p.position.set(-9.6+i*.49+(r%2)*.14,1.45+r*.46,-5.75+r*.1);scene.add(p)}
for(const x of [-6.3,-2.1,2.1,6.3]){const s=new THREE.SpotLight(0xffffff,24,24,Math.PI/9,.55,1.6);s.position.set(x,8.4,1.4);s.target.position.set(x*.18,.1,0);scene.add(s,s.target)}
const shadow=mk(new THREE.CircleGeometry(.95,42),new THREE.MeshBasicMaterial({color:0,transparent:true,opacity:.28,depthWrite:false}),false);shadow.rotation.x=-Math.PI/2;shadow.position.y=.1;shadow.scale.set(1.65,.72,1);scene.add(shadow);
const mat={skin:std(0xe1aa80,.8),skin2:std(0xbf855f,.84),shirt:std(0xef5a59,.74),accent:std(0xa83d45,.8),shorts:std(0x1b2a43,.78),shoe:std(0xf2f4f7,.62),sole:std(0x252a33,.84),hair:std(0x2a1b10,.95),white:std(0xffffff,.66),dark:std(0x0e1116,.8)};
const sphere=(r,m)=>mk(new THREE.SphereGeometry(r,22,18),m),cap=(r,l,m)=>mk(new THREE.CapsuleGeometry(r,l,8,18),m),box=(w,h,d,m)=>mk(new THREE.BoxGeometry(w,h,d),m);
const root=new THREE.Group(),rig=new THREE.Group();root.add(rig);scene.add(root);
const torso=cap(.36,.66,mat.shirt);torso.scale.set(1,.98,.9);torso.position.y=.68;rig.add(torso);const chest=box(.08,.44,.34,mat.accent);chest.position.set(.31,.68,0);rig.add(chest);const stripe=box(.025,.45,.22,mat.white);stripe.position.set(.365,.68,0);rig.add(stripe);
const pelvis=sphere(.34,mat.shorts);pelvis.scale.set(1,.68,.88);pelvis.position.y=-.03;rig.add(pelvis);const neck=cap(.075,.07,mat.skin);neck.position.y=1.15;rig.add(neck);
const head=new THREE.Group();head.position.set(0,1.52,0);rig.add(head);const face=sphere(.31,mat.skin);face.scale.set(.92,1.06,.9);head.add(face);const jaw=sphere(.19,mat.skin2);jaw.scale.set(.92,.68,.8);jaw.position.set(.05,-.14,0);head.add(jaw);const hair=sphere(.315,mat.hair);hair.scale.set(.96,.58,.92);hair.position.y=.18;head.add(hair);const nose=mk(new THREE.ConeGeometry(.04,.16,12),mat.skin2);nose.rotation.z=-Math.PI/2;nose.position.x=.31;head.add(nose);for(const z of [-.09,.09]){const e=sphere(.022,mat.dark);e.position.set(.235,.07,z);head.add(e)}
function arm(side){const s=new THREE.Group();s.position.set(.02,.98,side*.49);rig.add(s);const sleeve=cap(.14,.12,mat.shirt);sleeve.position.y=-.11;s.add(sleeve);const u=cap(.105,.42,mat.skin);u.position.y=-.36;s.add(u);const e=new THREE.Group();e.position.y=-.67;s.add(e);e.add(sphere(.105,mat.skin));const f=cap(.09,.38,mat.skin);f.position.y=-.29;e.add(f);const h=sphere(.095,mat.skin);h.scale.set(.82,1,.72);h.position.y=-.57;e.add(h);return{s,e}}
function leg(side){const h=new THREE.Group();h.position.set(0,-.14,side*.22);rig.add(h);const t=cap(.15,.5,mat.shorts);t.position.y=-.38;h.add(t);const k=new THREE.Group();k.position.y=-.74;h.add(k);k.add(sphere(.13,mat.skin));const sh=cap(.11,.46,mat.skin);sh.position.y=-.34;k.add(sh);const a=new THREE.Group();a.position.y=-.68;k.add(a);const f=box(.42,.13,.22,mat.shoe);f.position.set(.14,-.04,0);a.add(f);const so=box(.43,.04,.23,mat.sole);so.position.set(.14,-.115,0);a.add(so);return{h,k,a}}
const LA=arm(1),RA=arm(-1),LL=leg(1),RL=leg(-1),ROOT_Y=1.69;
function resetPose(){for(const j of [LA.s,RA.s,LA.e,RA.e,LL.h,RL.h,LL.k,RL.k,LL.a,RL.a])j.rotation.set(0,0,0);rig.rotation.set(0,0,0);rig.position.set(0,0,0);head.rotation.set(0,0,0)}
function runPose(t){resetPose();const p=t*Math.PI*4,s=Math.sin(p),o=-s;LL.h.rotation.z=s*.8;RL.h.rotation.z=o*.8;LL.k.rotation.z=s<0?-s*1.3:-s*.18;RL.k.rotation.z=o<0?-o*1.3:-o*.18;LL.a.rotation.z=s<0?-.15:.28;RL.a.rotation.z=o<0?-.15:.28;LA.s.rotation.z=o*.82;RA.s.rotation.z=s*.82;LA.e.rotation.z=.48+Math.max(0,-o)*.3;RA.e.rotation.z=.48+Math.max(0,-s)*.3;rig.rotation.z=-.14;rig.position.y=Math.max(0,Math.sin(p))*.035;head.rotation.y=.04}
function crouch(v=1,one=false){resetPose();LL.h.rotation.z=-.82*v;RL.h.rotation.z=(one?-1.08:-.82)*v;LL.k.rotation.z=1.55*v;RL.k.rotation.z=(one?1.9:1.55)*v;LL.a.rotation.z=-.35*v;RL.a.rotation.z=-.4*v;LA.s.rotation.z=-1.45*v;RA.s.rotation.z=-1.7*v;LA.e.rotation.z=.45*v;RA.e.rotation.z=.55*v;rig.rotation.z=-.16*v;rig.position.y=-.22*v}
function tuck(v=1){resetPose();LL.h.rotation.z=RL.h.rotation.z=-1.38*v;LL.k.rotation.z=RL.k.rotation.z=2.15*v;LA.s.rotation.z=RA.s.rotation.z=-.95*v;LA.e.rotation.z=RA.e.rotation.z=1.15*v}
function layout(){resetPose();LL.h.rotation.z=RL.h.rotation.z=-.18;LA.s.rotation.z=RA.s.rotation.z=-.55;LA.e.rotation.z=RA.e.rotation.z=.22}
function side(){resetPose();LA.s.rotation.x=-1.1;RA.s.rotation.x=1.1;LL.h.rotation.z=-.28;RL.h.rotation.z=.28;LL.k.rotation.z=RL.k.rotation.z=.55}
const chars=[{id:'rookie',name:'Rookie',price:0,shirt:0xef5a59,a:0xa83d45,shorts:0x1b2a43,skin:0xe1aa80,skin2:0xbf855f,hair:0x2a1b10,desc:'Balanced default athlete.'},{id:'neon',name:'Neon',price:180,shirt:0x51efc1,a:0x1ea780,shorts:0x121a23,skin:0xe1aa80,skin2:0xbf855f,hair:0x111111,desc:'Bright competition fit.'},{id:'midnight',name:'Midnight',price:260,shirt:0x5d74f5,a:0x364ab4,shorts:0x0b1017,skin:0xb97855,skin2:0x8f563a,hair:0x0f0a08,desc:'Dark arena setup.'},{id:'gold',name:'Gold Pro',price:420,shirt:0xf2c24e,a:0xb88722,shorts:0x32230b,skin:0xd59b74,skin2:0xaf7756,hair:0x2a190d,desc:'Show-off mode.'}];
function applyChar(id){const c=chars.find(x=>x.id===id)||chars[0];mat.shirt.color.setHex(c.shirt);mat.accent.color.setHex(c.a);mat.shorts.color.setHex(c.shorts);mat.skin.color.setHex(c.skin);mat.skin2.color.setHex(c.skin2);mat.hair.color.setHex(c.hair)}applyChar(save.equippedCharacter);
const tricks=[{id:'backflip',name:'Backflip',difficulty:'Beginner',price:0,mode:'standing',axis:'back',turns:1,height:2.35,travel:.12,note:'Standing backflip: mostly vertical backward rotation.'},{id:'frontflip',name:'Frontflip',difficulty:'Beginner',price:0,mode:'run',axis:'front',turns:1,height:2.05,travel:2.2,note:'Forward rotation while traveling forward.'},{id:'sideflip',name:'Sideflip',difficulty:'Beginner',price:0,mode:'run',axis:'side',turns:1,height:2.05,travel:1.95,note:'Sideways barrel rotation.'},{id:'spin360',name:'360 Spin',difficulty:'Intermediate',price:0,mode:'run',axis:'spin',turns:1,height:1.75,travel:1.9,note:'Upright twist around the vertical axis.'},{id:'gainer',name:'Gainer',difficulty:'Intermediate',price:160,mode:'run',axis:'back',turns:1,height:2.15,travel:2.55,one:true,note:'Forward travel with backward rotation from one leg.'},{id:'cork360',name:'Cork 360',difficulty:'Intermediate',price:220,mode:'run',axis:'cork',turns:1,height:2.35,travel:2.15,note:'Off-axis flip blended with a twist.'},{id:'doubleback',name:'Double Backflip',difficulty:'Advanced',price:320,mode:'standing',axis:'back',turns:2,height:2.95,travel:.16,note:'Two backward rotations from a vertical takeoff.'},{id:'doublefront',name:'Double Frontflip',difficulty:'Advanced',price:360,mode:'run',axis:'front',turns:2,height:2.78,travel:2.3,note:'Two forward rotations while traveling.'},{id:'cork720',name:'Cork 720',difficulty:'Expert',price:520,mode:'run',axis:'cork',turns:2,height:2.8,travel:2.25,note:'Off-axis flip with extra twist.'}];
let score=0,round=1,lives=3,combo=1,current=null,locked=false,anim=null;
const owned=()=>tricks.filter(t=>save.ownedTricks.includes(t.id)),hud=()=>{scoreEl.textContent=score;roundEl.textContent=round;livesEl.textContent=lives;comboEl.textContent='×'+combo;coinsEl.textContent=save.coins;shopCoins.textContent=save.coins},shuffle=a=>[...a].sort(()=>Math.random()-.5);
function renderAnswers(){answersEl.innerHTML='';for(const o of shuffle([current,...shuffle(tricks.filter(t=>t.id!==current.id)).slice(0,3)])){const b=document.createElement('button');b.className='answer-btn';b.textContent=o.name;b.onclick=()=>guess(o,b);answersEl.appendChild(b)}}
function quat(t,p){const a=Math.PI*2*t.turns*p,q=new THREE.Quaternion();if(t.axis==='front')q.setFromAxisAngle(new THREE.Vector3(0,0,1),-a);else if(t.axis==='back')q.setFromAxisAngle(new THREE.Vector3(0,0,1),a);else if(t.axis==='side')q.setFromAxisAngle(new THREE.Vector3(1,0,0),a);else if(t.axis==='spin')q.setFromAxisAngle(new THREE.Vector3(0,1,0),-a);else q.copy(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),-a)).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),a*.74));return q}
function airPose(t,p){if(t.axis==='spin'||t.axis==='cork')layout();else if(t.axis==='side')side();else tuck(.45+.55*Math.sin(Math.PI*p))}
function animate(t,sl=false){if(anim)cancelAnimationFrame(anim);const st=performance.now(),dur=(sl?2.3:1)*(t.mode==='standing'?2500:3000),run=t.mode==='run'?.33:.18,air=.84,startX=t.mode==='run'?-4.5:0,takeX=t.mode==='run'?-1:0,landX=takeX+t.travel;status.textContent=sl?'SLOW MOTION':'WATCH THE TRICK';function f(now){const x=Math.min(1,(now-st)/dur);root.quaternion.identity();if(x<run){const r=x/run;if(t.mode==='run'){root.position.set(THREE.MathUtils.lerp(startX,takeX,r),ROOT_Y,0);r<.8?runPose(r/.8):crouch((r-.8)/.2,!!t.one)}else{root.position.set(0,ROOT_Y,0);crouch(Math.sin(r*Math.PI)*.95)}}else if(x<air){const p=(x-run)/(air-run);root.position.set(THREE.MathUtils.lerp(takeX,landX,p),ROOT_Y+4*t.height*p*(1-p),0);root.quaternion.copy(quat(t,p));airPose(t,p)}else{const l=(x-air)/(1-air);root.position.set(landX,ROOT_Y,0);root.quaternion.identity();crouch(.7*Math.max(0,1-l))}shadow.position.x=root.position.x;const h=Math.max(0,root.position.y-ROOT_Y);shadow.material.opacity=.28*Math.max(.24,1-h/4.5);shadow.scale.set(1.65+h*.14,.72+h*.05,1);renderer.render(scene,camera);if(x<1)anim=requestAnimationFrame(f);else{status.textContent='MAKE YOUR CALL';anim=null}}anim=requestAnimationFrame(f)}
function next(){locked=false;const p=owned();let n=p[Math.floor(Math.random()*p.length)];if(current&&p.length>1)while(n.id===current.id)n=p[Math.floor(Math.random()*p.length)];current=n;difficulty.textContent=n.difficulty;feedback.textContent='Watch the takeoff, travel direction and rotation axis.';renderAnswers();animate(n)}
function guess(o,b){if(locked||lives<=0)return;locked=true;const bs=[...answersEl.children];bs.forEach(x=>x.disabled=true);bs.find(x=>x.textContent===current.name)?.classList.add('correct');if(o.id===current.id){b.classList.add('correct');const pts=100*combo,c=12+Math.min(18,(combo-1)*3);score+=pts;save.coins+=c;combo=Math.min(8,combo+1);persist();feedback.textContent=`Correct — +${pts} score, +${c} coins. ${current.note}`;status.textContent='CORRECT'}else{b.classList.add('wrong');lives--;combo=1;score=Math.max(0,score-50);feedback.textContent=`Wrong. That was ${current.name}. ${current.note}`;status.textContent='WRONG'}hud();if(lives<=0){restartBtn.classList.remove('hidden');feedback.textContent+=` Game over — ${score} points.`;return}setTimeout(()=>{round++;hud();next()},1500)}
function restart(){score=0;round=1;lives=3;combo=1;restartBtn.classList.add('hidden');hud();next()}
function renderShop(){charShop.innerHTML='';trickShop.innerHTML='';hud();for(const c of chars){const own=save.ownedCharacters.includes(c.id),eq=save.equippedCharacter===c.id,d=document.createElement('div');d.className='shop-item '+(own?'owned':'');d.innerHTML=`<div class="shop-swatch" style="background:#${c.shirt.toString(16).padStart(6,'0')}">●</div><div class="shop-copy"><strong>${c.name}</strong><small>${c.desc}</small><div class="shop-price"><span class="coin-dot"></span>${c.price}</div></div><div class="shop-action-wrap"><button class="shop-action ${own?'':'buy'} ${eq?'equipped':''}">${eq?'Equipped':own?'Equip':'Buy'}</button></div>`;d.querySelector('button').onclick=()=>{if(eq)return;if(own){save.equippedCharacter=c.id;applyChar(c.id);persist();shopMsg.textContent=`Equipped ${c.name}.`;renderShop();return}if(save.coins<c.price){shopMsg.textContent='Not enough coins.';return}save.coins-=c.price;save.ownedCharacters.push(c.id);save.equippedCharacter=c.id;applyChar(c.id);persist();shopMsg.textContent=`Bought ${c.name}.`;renderShop()};charShop.appendChild(d)}for(const t of tricks.filter(t=>t.price)){const own=save.ownedTricks.includes(t.id),d=document.createElement('div');d.className='shop-item '+(own?'owned':'');d.innerHTML=`<div class="shop-swatch" style="background:#243043;color:#fff">↻</div><div class="shop-copy"><strong>${t.name}</strong><small>${t.note}</small><div class="shop-price"><span class="coin-dot"></span>${t.price}</div></div><div class="shop-action-wrap"><button class="shop-action ${own?'equipped':'buy'}" ${own?'disabled':''}>${own?'Owned':'Unlock'}</button></div>`;d.querySelector('button').onclick=()=>{if(own)return;if(save.coins<t.price){shopMsg.textContent='Not enough coins.';return}save.coins-=t.price;save.ownedTricks.push(t.id);persist();shopMsg.textContent=`Unlocked ${t.name}.`;renderShop()};trickShop.appendChild(d)}}
$('#shopBtn').onclick=()=>{renderShop();shopMsg.textContent='';shop.showModal()};$('#closeShop').onclick=()=>shop.close();shop.onclick=e=>{if(e.target===shop)shop.close()};const how=$('#howDialog');$('#howBtn').onclick=()=>how.showModal();$('#closeHow').onclick=()=>how.close();how.onclick=e=>{if(e.target===how)how.close()};replay.onclick=()=>current&&animate(current);slow.onclick=()=>current&&animate(current,true);restartBtn.onclick=restart;
function resize(){const w=arena.clientWidth,h=arena.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera)}new ResizeObserver(resize).observe(arena);addEventListener('resize',resize);hud();resize();next();
