import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s),canvas=$('#arenaCanvas'),arena=$('#arena'),status=$('#statusText'),feedback=$('#feedback');
const scoreEl=$('#score'),roundEl=$('#round'),livesEl=$('#lives'),comboEl=$('#combo'),coinsEl=$('#coins'),answers=$('#answers'),difficulty=$('#difficulty');
const shop=$('#shopDialog'),charShop=$('#characterShop'),trickShop=$('#trickShop'),shopCoins=$('#shopCoins'),shopMsg=$('#shopMessage');
const SAVE='trickJudgeSaveV4',defaults={coins:0,ownedCharacters:['rookie'],equippedCharacter:'rookie',ownedTricks:['backflip','frontflip','sideflip','spin360']};
let save;try{save={...defaults,...JSON.parse(localStorage.getItem(SAVE)||localStorage.getItem('trickJudgeSaveV3')||'{}')}}catch{save={...defaults}}const persist=()=>localStorage.setItem(SAVE,JSON.stringify(save));
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'})}catch(e){$('#webglError').classList.remove('hidden');throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x2b4764);scene.fog=new THREE.Fog(0x2b4764,28,60);
const camera=new THREE.PerspectiveCamera(39,1,.1,100);camera.position.set(.4,4.2,13.9);camera.lookAt(.1,2.1,-.6);
scene.add(new THREE.HemisphereLight(0xe7f2ff,0x65717c,2.7));const key=new THREE.DirectionalLight(0xffffff,3.5);key.position.set(-5,11,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new THREE.DirectionalLight(0xa7caff,1.1);rim.position.set(6,5,-7);scene.add(rim);
const M=(c,r=.85,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m}),B=(w,h,d,mat,x=0,y=0,z=0)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return o};
const world=new THREE.Group();scene.add(world);const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,20),M(0x284766,.94));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;world.add(floor,B(19.2,.055,8.9,M(0x365f88,.9),0,.025,-.1));
const white=M(0xf5f8fc,.6);for(const z of[-3.55,-2.15,2.15,3.55])world.add(B(18.3,.02,.05,white,0,.066,z));for(const x of[-8.45,-3.35,3.35,8.45])world.add(B(.05,.02,7.1,white,x,.066,0));
world.add(B(5.7,.46,1.8,M(0x163f72,.78),-.5,.27,-2.45),B(5.55,.12,1.67,M(0x2d6aa0,.72),-.5,.56,-2.45),B(24.5,10.8,.28,M(0x22384f,.96),0,5.3,-8.5));
for(let r=0;r<8;r++)world.add(B(20.5,.26,.73,M(r%2?0x2c445f:0x20364e,.95),0,1.18+r*.46,-4.35-r*.49));
const seatGeo=new THREE.BoxGeometry(.34,.23,.38),seats=new THREE.InstancedMesh(seatGeo,M(0x1b3555,.84),288),d=new THREE.Object3D();let ii=0;for(let r=0;r<8;r++)for(let i=0;i<36;i++){const gap=i==10||i==11||i==24||i==25;d.position.set(-9.1+i*.52,1.46+r*.46,-4.08-r*.49);d.scale.setScalar(gap?.001:1);d.updateMatrix();seats.setMatrixAt(ii++,d.matrix)}seats.instanceMatrix.needsUpdate=true;world.add(seats);
const hg=new THREE.SphereGeometry(.105,10,8),tg=new THREE.CapsuleGeometry(.11,.2,3,8),hm=M(0xc79677,.92),tops=[0x7c8795,0x8a635f,0x60768e,0x75637d,0x72836b,0x846f55,0x4e6977].map(c=>M(c,.96));for(let r=0;r<5;r++)for(let i=0;i<30;i++){if((i>=9&&i<=11)||(i>=21&&i<=23))continue;const x=-8.7+i*.59+(r%2)*.12,y=1.95+r*.47,z=-4-r*.49,t=new THREE.Mesh(tg,tops[(r+i)%tops.length]),h=new THREE.Mesh(hg,hm);t.position.set(x,y-.11,z);t.scale.set(.9,1.15,.86);h.position.set(x,y+.22,z);world.add(t,h)}
const rail=M(0xa4b2bf,.45,.65);world.add(B(20,.055,.055,rail,0,2.06,-3.66));for(let i=0;i<18;i++)world.add(B(.05,.82,.05,rail,-8.6+i*1.02,1.66,-3.66));
for(const x of[-7.2,0,7.2]){world.add(B(2.55,1.45,.14,M(0x172638,.65,.3),x,6.95,-8),B(2.25,1.12,.04,new THREE.MeshBasicMaterial({color:0xdce9f6}),x,6.95,-7.9))}
for(const x of[-7.5,-2.5,2.5,7.5]){world.add(B(1.45,.18,.28,M(0x3a4652,.5,.55),x,8.55,-1.8));const l=new THREE.SpotLight(0xffffff,18,22,Math.PI/8,.55,1.5);l.position.set(x,8.4,-1.5);l.target.position.set(x*.15,0,0);scene.add(l,l.target)}
const shadow=new THREE.Mesh(new THREE.CircleGeometry(.62,40),new THREE.MeshBasicMaterial({color:0x071522,transparent:true,opacity:.31,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.09;shadow.scale.set(1.55,.65,1);scene.add(shadow);
const root=new THREE.Group(),pivot=new THREE.Group();root.add(pivot);scene.add(root);const HEIGHT=1.83,ROOTY=HEIGHT/2+.07;let model=null,mixer=null,runClip=null,runAction=null,ready=false,bones={},base=new Map(),anim=null;
const chars=[{id:'rookie',name:'Rookie',price:0,top:0xa83f49,bottom:0x34465f,hair:0x402c21,desc:'Red competition outfit.'},{id:'neon',name:'Neon',price:180,top:0x32cfa5,bottom:0x172431,hair:0x171717,desc:'Bright performance outfit.'},{id:'midnight',name:'Midnight',price:260,top:0x4659c9,bottom:0x141a25,hair:0x15100d,desc:'Dark blue arena outfit.'},{id:'gold',name:'Gold Pro',price:420,top:0xd9a532,bottom:0x49371d,hair:0x3c2717,desc:'Gold pro kit.'}];
function skin(id){if(!model)return;const c=chars.find(x=>x.id===id)||chars[0];model.traverse(o=>{if(!o.isMesh)return;for(const m of(Array.isArray(o.material)?o.material:[o.material])){const n=(o.name+' '+m.name).toLowerCase();if(!m.color)continue;if(n.includes('hair'))m.color.setHex(c.hair);else if(/bottom|pants|trouser|jean/.test(n))m.color.setHex(c.bottom);else if(/outfit|top|shirt|hood|jacket/.test(n))m.color.setHex(c.top)}})}
function bone(...names){let f=null;model?.traverse(o=>{if(f||!o.isBone)return;const n=o.name.toLowerCase().replace(/[^a-z0-9]/g,'');if(names.some(v=>n.includes(v)))f=o});return f}
function mapBones(){bones={hips:bone('hips'),chest:bone('spine2','chest'),head:bone('head'),la:bone('leftupperarm','leftarm'),ra:bone('rightupperarm','rightarm'),lf:bone('leftforearm'),rf:bone('rightforearm'),lt:bone('leftupleg','leftthigh'),rt:bone('rightupleg','rightthigh'),ls:bone('leftleg','leftcalf'),rs:bone('rightleg','rightcalf')};base.clear();model.traverse(o=>{if(o.isBone)base.set(o,{q:o.quaternion.clone(),p:o.position.clone()})})}
function reset(){base.forEach((v,b)=>{b.quaternion.copy(v.q);b.position.copy(v.p)})}function add(b,x=0,y=0,z=0){if(!b||!base.has(b))return;b.quaternion.copy(base.get(b).q).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(x,y,z)))}
function stand(){reset();add(bones.la,0,0,-1.25);add(bones.ra,0,0,1.25)}function crouch(v=1,one=false){stand();add(bones.lt,-.62*v);add(bones.rt,(one?-.92:-.62)*v);add(bones.ls,1.18*v);add(bones.rs,(one?1.55:1.18)*v);add(bones.la,-.65*v,0,-1.25);add(bones.ra,-.65*v,0,1.25)}function tuck(v=1){stand();add(bones.lt,-1.18*v);add(bones.rt,-1.18*v);add(bones.ls,1.95*v);add(bones.rs,1.95*v);add(bones.la,-.9*v,0,-1.05);add(bones.ra,-.9*v,0,1.05);add(bones.lf,-1.05*v);add(bones.rf,-1.05*v)}function layout(){stand();add(bones.la,-.3,0,-1);add(bones.ra,-.3,0,1);add(bones.lt,-.12);add(bones.rt,-.12)}function side(){stand();add(bones.la,-.1,-.6,-.9);add(bones.ra,.1,.6,.9);add(bones.lt,-.25,0,.1);add(bones.rt,-.25,0,-.1)}
const loader=new GLTFLoader(),AV='https://models.readyplayer.me/6185a4acfb622cf1cdc49348.glb?pose=T&quality=high',RUN='https://raw.githubusercontent.com/readyplayerme/animation-library/master/masculine/glb/locomotion/F_Run_001.glb';
loader.load(AV,g=>{model=g.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone()}});pivot.add(model);model.updateMatrixWorld(true);let bb=new THREE.Box3().setFromObject(model),sz=new THREE.Vector3();bb.getSize(sz);model.scale.setScalar(HEIGHT/sz.y);model.updateMatrixWorld(true);bb=new THREE.Box3().setFromObject(model);const c=new THREE.Vector3();bb.getCenter(c);model.position.sub(c);model.rotation.y=Math.PI/2;mapBones();stand();skin(save.equippedCharacter);root.position.set(-4.7,ROOTY,0);ready=true;status.textContent='ATHLETE READY';loader.load(RUN,a=>{if(a.animations?.length){runClip=a.animations[0].clone();runClip.tracks=runClip.tracks.filter(t=>!/hips\.position|hip\.position/i.test(t.name));mixer=new THREE.AnimationMixer(model);runAction=mixer.clipAction(runClip);runAction.play()}status.textContent='WATCH THE TRICK';newRound()},undefined,()=>newRound())},undefined,e=>{console.error(e);status.textContent='ATHLETE LOAD FAILED';feedback.textContent='The realistic athlete failed to load. Refresh and try again.'});
const tricks=[{id:'backflip',name:'Backflip',difficulty:'Beginner',price:0,mode:'standing',axis:'back',turns:1,height:2.15,travel:-.12,note:'Standing backward rotation with almost no travel.'},{id:'frontflip',name:'Frontflip',difficulty:'Beginner',price:0,mode:'run',axis:'front',turns:1,height:2,travel:2.1,note:'Forward rotation while traveling forward.'},{id:'sideflip',name:'Sideflip',difficulty:'Beginner',price:0,mode:'run',axis:'side',turns:1,height:2,travel:1.9,note:'Sideways barrel rotation.'},{id:'spin360',name:'360 Spin',difficulty:'Intermediate',price:0,mode:'run',axis:'spin',turns:1,height:1.65,travel:1.8,note:'Mostly upright vertical-axis twist.'},{id:'gainer',name:'Gainer',difficulty:'Intermediate',price:160,mode:'run',axis:'back',turns:1,height:2.15,travel:2.5,oneLeg:true,note:'Forward travel with backward rotation.'},{id:'cork360',name:'Cork 360',difficulty:'Intermediate',price:220,mode:'run',axis:'cork',turns:1,height:2.25,travel:2.1,note:'Off-axis flip blended with a twist.'},{id:'doubleback',name:'Double Backflip',difficulty:'Advanced',price:320,mode:'standing',axis:'back',turns:2,height:2.7,travel:-.14,note:'Two backward rotations.'},{id:'doublefront',name:'Double Frontflip',difficulty:'Advanced',price:360,mode:'run',axis:'front',turns:2,height:2.6,travel:2.25,note:'Two forward rotations.'},{id:'cork720',name:'Cork 720',difficulty:'Expert',price:520,mode:'run',axis:'cork',turns:2,height:2.7,travel:2.2,note:'Large off-axis twisting rotation.'}];
let score=0,round=1,lives=3,combo=1,current=null,locked=false;const owned=()=>tricks.filter(t=>save.ownedTricks.includes(t.id)),shuffle=a=>[...a].sort(()=>Math.random()-.5);function hud(){scoreEl.textContent=score;roundEl.textContent=round;livesEl.textContent=lives;comboEl.textContent='×'+combo;coinsEl.textContent=save.coins;shopCoins.textContent=save.coins}function opts(t){return shuffle([t,...shuffle(tricks.filter(x=>x.id!==t.id)).slice(0,3)])}function renderAnswers(){answers.innerHTML='';for(const o of opts(current)){const b=document.createElement('button');b.className='answer-btn';b.textContent=o.name;b.onclick=()=>guess(o,b);answers.appendChild(b)}}
function qFor(t,p){const a=Math.PI*2*t.turns*p,q=new THREE.Quaternion();if(t.axis==='front')q.setFromAxisAngle(new THREE.Vector3(0,0,1),-a);else if(t.axis==='back')q.setFromAxisAngle(new THREE.Vector3(0,0,1),a);else if(t.axis==='side')q.setFromAxisAngle(new THREE.Vector3(1,0,0),a);else if(t.axis==='spin')q.setFromAxisAngle(new THREE.Vector3(0,1,0),-a);else q.copy(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),-a)).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),a*.72));return q}function airPose(t,p){if(t.axis==='spin'||t.axis==='cork')layout();else if(t.axis==='side')side();else tuck(.5+.5*Math.sin(Math.PI*p))}
function manualRun(p){stand();const ph=p*Math.PI*8,s=Math.sin(ph);add(bones.lt,-.65*s);add(bones.rt,.65*s);add(bones.ls,Math.max(0,s)*.9);add(bones.rs,Math.max(0,-s)*.9);add(bones.la,.6*s,0,-1.25);add(bones.ra,-.6*s,0,1.25)}function runPose(p){if(!mixer||!runClip||!runAction)return manualRun(p);mixer.setTime((p*2.25*runClip.duration)%runClip.duration)}
function play(t,slow=false){if(!ready)return;if(anim)cancelAnimationFrame(anim);locked=false;const start=performance.now(),dur=(slow?2.35:1)*(t.mode==='standing'?2450:2950),runEnd=t.mode==='run'?.34:.18,airEnd=.84,sx=t.mode==='run'?-4.7:0,tx=t.mode==='run'?-1:0,lx=tx+t.travel;status.textContent=slow?'SLOW MOTION':'WATCH THE TRICK';function frame(now){const u=Math.min(1,(now-start)/dur);root.quaternion.identity();if(u<runEnd){const r=u/runEnd;if(t.mode==='run'){root.position.set(THREE.MathUtils.lerp(sx,tx,r),ROOTY,0);r<.8?runPose(r/.8):crouch((r-.8)/.2,!!t.oneLeg)}else{root.position.set(0,ROOTY,0);crouch(Math.sin(r*Math.PI)*.92)}}else if(u<airEnd){const p=(u-runEnd)/(airEnd-runEnd);root.position.set(THREE.MathUtils.lerp(tx,lx,p),ROOTY+4*t.height*p*(1-p),0);root.quaternion.copy(qFor(t,p));airPose(t,p)}else{const l=(u-airEnd)/(1-airEnd);root.position.set(lx,ROOTY,0);crouch(Math.max(0,.72*(1-l)));if(l>.55)stand()}shadow.position.x=root.position.x;const h=Math.max(0,root.position.y-ROOTY);shadow.material.opacity=.31*Math.max(.22,1-h/4.2);renderer.render(scene,camera);if(u<1)anim=requestAnimationFrame(frame);else{stand();status.textContent='MAKE YOUR CALL';anim=null}}anim=requestAnimationFrame(frame)}
function newRound(){if(!ready)return;locked=false;const pool=owned();let n=pool[Math.floor(Math.random()*pool.length)];while(current&&pool.length>1&&n.id===current.id)n=pool[Math.floor(Math.random()*pool.length)];current=n;difficulty.textContent=n.difficulty;feedback.textContent='Watch the takeoff, travel direction and rotation axis.';renderAnswers();play(n)}function guess(o,b){if(locked||lives<=0)return;locked=true;const bs=[...answers.querySelectorAll('button')];bs.forEach(x=>x.disabled=true);bs.find(x=>x.textContent===current.name)?.classList.add('correct');if(o.id===current.id){b.classList.add('correct');const pts=100*combo,coins=12+Math.min(18,(combo-1)*3);score+=pts;save.coins+=coins;combo=Math.min(8,combo+1);persist();feedback.textContent=`Correct — +${pts} score, +${coins} coins. ${current.note}`;status.textContent='CORRECT'}else{b.classList.add('wrong');lives--;combo=1;score=Math.max(0,score-50);feedback.textContent=`Wrong. That was ${current.name}. ${current.note}`;status.textContent='WRONG'}hud();if(lives<=0){$('#restartBtn').classList.remove('hidden');feedback.textContent+=` Game over — ${score} points.`;return}setTimeout(()=>{round++;hud();newRound()},1500)}
function renderShop(){charShop.innerHTML=trickShop.innerHTML='';hud();for(const c of chars){const own=save.ownedCharacters.includes(c.id),eq=save.equippedCharacter===c.id,e=document.createElement('div');e.className='shop-item '+(own?'owned':'');e.innerHTML=`<div class="shop-swatch" style="background:#${c.top.toString(16).padStart(6,'0')}">●</div><div class="shop-copy"><strong>${c.name}</strong><small>${c.desc}</small><div class="shop-price"><span class="coin-dot"></span>${c.price}</div></div><div class="shop-action-wrap"><button class="shop-action ${own?'':'buy'} ${eq?'equipped':''}">${eq?'Equipped':own?'Equip':'Buy'}</button></div>`;e.querySelector('button').onclick=()=>{if(eq)return;if(own){save.equippedCharacter=c.id;skin(c.id);persist()}else if(save.coins>=c.price){save.coins-=c.price;save.ownedCharacters.push(c.id);save.equippedCharacter=c.id;skin(c.id);persist()}else return shopMsg.textContent='Not enough coins.';renderShop()};charShop.appendChild(e)}for(const t of tricks.filter(x=>x.price>0)){const own=save.ownedTricks.includes(t.id),e=document.createElement('div');e.className='shop-item '+(own?'owned':'');e.innerHTML=`<div class="shop-swatch" style="background:#24364b;color:#fff">↻</div><div class="shop-copy"><strong>${t.name}</strong><small>${t.note}</small><div class="shop-price"><span class="coin-dot"></span>${t.price}</div></div><div class="shop-action-wrap"><button class="shop-action ${own?'equipped':'buy'}" ${own?'disabled':''}>${own?'Owned':'Unlock'}</button></div>`;e.querySelector('button').onclick=()=>{if(own)return;if(save.coins<t.price)return shopMsg.textContent='Not enough coins.';save.coins-=t.price;save.ownedTricks.push(t.id);persist();renderShop()};trickShop.appendChild(e)}}
$('#shopBtn').onclick=()=>{renderShop();shopMsg.textContent='';shop.showModal()};$('#closeShop').onclick=()=>shop.close();const how=$('#howDialog');$('#howBtn').onclick=()=>how.showModal();$('#closeHow').onclick=()=>how.close();$('#replayBtn').onclick=()=>current&&play(current);$('#slowBtn').onclick=()=>current&&play(current,true);$('#restartBtn').onclick=()=>{score=0;round=1;lives=3;combo=1;$('#restartBtn').classList.add('hidden');hud();newRound()};
function resize(){const w=arena.clientWidth,h=arena.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.render(scene,camera)}new ResizeObserver(resize).observe(arena);addEventListener('resize',resize);hud();resize();status.textContent='LOADING REAL ATHLETE';